 group:

    # Things for modules ONLY!
  - files:
      - source: .github/workflows/module-packager.yml
        dest:  .github/workflows/module-packager.yml
    repos: |
      N6REJ/mod_bears_pricing_tables
      N6REJ/mod_julianclock
      N6REJ/module_bearsclock
