theme: jekyll-theme-hacker
title: [Bear's Git page]
description: [Joomla Packager Documentation]
navigation:
  - title: "Packager Documentation"
    url: https://git.hallhome.us/joomla-module-workflow-article.html
