theme: minima
title: Bear's Git page
description: About me

# Navigation for minima theme
nav_pages:
  - title: "Home"
    url: /
  - title: Packager Documentation
    url: /joomla-module-workflow-article.html
