plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-default-layout
title: [Bear's Git page]
description: [Joomal Packager Documentation]
remote_theme: just-the-docs/just-the-docs

url: https://N6REJ.github.io/n6rej.github.io

aux_links: # remove if you don't want this link to appear on your pages
  View on Github: https://github.com/N6REJ/n6rej.github.io
  Hallhome.us: https://hallhome.us
